---
- name: Add PPA for Nginx (if configured).
  become: yes
  apt_repository:
    repo: 'ppa:nginx/{{ nginx_ppa_version }}'
    state: present
    update_cache: true
  register: nginx_ppa_added
  when: nginx_ppa_use | bool

- name: Ensure nginx will reinstall if the PPA was just added.
  become: yes
  apt:
    name: "{{ nginx_package_name }}"
    state: absent
  when: nginx_ppa_added is changed