---
# We create the required consul configuration folders
- name: config | creating consul configuration folders
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  become: true
  loop:
    - "{{ consul_client_config_dir }}"
    - "{{ consul_client_config_dir + '/client' }}"
    - "{{ consul_client_config_dir + '/scripts' }}"

# We create the consul data folder
- name: config | creating consul data folder
  file:
    path: "{{ consul_client_configuration.data_dir }}"
    owner: "{{ consul_client_user_info.user }}"
    group: "{{ consul_client_user_info.group }}"
    recurse: yes
    state: directory
  become: true

- name: config | configuring consul
  template:
    src: config.json.j2
    dest: "{{ consul_client_config_dir + '/client/config.json' }}"
    owner: root
    group: root
    mode: 644
  become: true
  notify:
    - restart consul-client
