---
# Define Ansible group for Consul servers
consul_servers_group: aws_consul
consul_nginx_group: aws_nginx
# Define interface to bind to...(eth0|eth1|enp0s8)
consul_bind_interface: "{{ ansible_default_ipv4['interface'] | replace('-', '_') }}"

ipv4: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses) }}"

consul_client_bind_interface: eth0

consul_client_config_dir: /etc/consul.d
consul_client_config_file: /etc/consul.conf

#https://www.consul.io/docs/agent/options.html
consul_client_configuration:
  data_dir: /var/consul/data

  



consul_client_install_dir: /usr/bin

# Define Consul user info to use for service
consul_client_user_info:
  user: consul
  group: consul

consul_client_version: 1.12.3
